# This has to be >= v1.57.0 for module plugin system support.
version: v1.63.4
destination: ./build/
name: custom-gcl
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest # Or a fixed version for reproducible builds.