name: Publish Artifact

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release"
        required: true
        default: ""
        type: string
  workflow_call:
    inputs:
      tag_name:
        description: "Tag to release"
        required: true
        default: ""
        type: string
    secrets:
      MACOS_SIGN_PASSWORD:
        required: true
      MACOS_SIGN_P12:
        required: true
      MACOS_NOTARY_ISSUER_ID:
        required: true
      MACOS_NOTARY_KEY_ID:
        required: true
      MACOS_NOTARY_KEY:
        required: true

env:
  GOMODCACHE: /home/runner/go/pkg/mod
  GOCACHE: /home/runner/go/pkg/mod/build-cache
  CONTAINIFYCI_CACHE: /home/runner/go/pkg/mod
  CONTAINIFYCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CONTAINIFYCI_FILE: .containifyci/containifyci.go
  CONTAINIFYCI_GITHUB_REF: refs/tags/${{ inputs.tag_name }}
  GORELEASER_CURRENT_TAG: ${{ inputs.tag_name }}

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0

      - name: Update major and minor release tags
        uses: rickstaa/action-update-semver@v1
        with:
          tag: ${{ inputs.tag_name }}

      - name: Cache Go Mod
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          save-always: true

      - name: Install Engine CI
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: containifyci/engine-ci
          # At the moment fetch latest release
          # version: ${{ inputs.version }}
          cache: true
          extension-matching: disable
          rename-to: engine-ci
          chmod: 0755

      - name: Release
        run: |
          engine-ci engine -t release
        env:
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
          MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
          MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
