name: Build with ContainifyCI workflow

on:
  workflow_call:

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build:
    name: Build
    uses: containifyci/engine-ci/.github/workflows/engine-ci-workflow.yml@v0
    secrets: inherit
    with:
      install_binary: true
      dockerhub_user: "containifyci"
