name: golangci-lint Test

on:
  workflow_dispatch:

concurrency:
  group: go_mask_lint_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run golangci-lint
      uses: containifyci/.github/github-actions/golangci-lint@main
      continue-on-error: true
    - name: Run golangci-lint
      uses: containifyci/.github/github-actions/golangci-lint@main
      with:
        args: "--no-config"
        working-directory: ".containifyci"
