name: golangci-lint Test

on:
  workflow_dispatch:

concurrency:
  group: go_mask_lint_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run golangci-lint
      uses: containifyci/.github/.github/github-actions/golangci-lint@v1
