name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: go_mask_publish_${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout

jobs:
  publish:
    uses: containifyci/engine-ci/.github/workflows/artifact.yaml@v0
    secrets: inherit
    with:
      tag_name: ${{ github.event.release.tag_name }}
