name: Publish

on:
  release:
    types: [published]

concurrency:
  group: go_mask_publish_${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout

jobs:
  publish:
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    with:
      tag_name: ${{ github.event.release.tag_name }}
