name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

concurrency:
  group: go-mask_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build-go-mask:
    uses: ./.github/workflows/containifyci.yaml
    secrets: inherit
